version: '3'
services:
  jenkins:
    image: harbor.chay-techs.com/jenkins/jenkins:latest  # Full image URL from the Harbor registry
    container_name: jenkins
    ports:
      - 8081:8080
    volumes:
      - ${DOCKERSOCK}:/var/run/docker.sock 
      - ${JENKINS_HOME}:/var/jenkins_home:rw
