version: '3'
services:
  jenkins:
    build: .
    #image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /home/yechezke/volumes/jenkins/jenkins_home:/var/jenkins_home:rw
