version: '3'
services:
  jenkins:
    image: harbor.chay-techs.com/jenkins/jenkins-app:latest  # Full image URL from the Harbor registry
    container_name: jenkins
    volumes:
      - ${DOCKERSOCK}:/var/run/docker.sock 
      - ${JENKINS_HOME}:/var/jenkins_home:rw
  nginx:
    image: harbor.chay-techs.com/jenkins/nginx:latest
    ports:
      - 8082:8080
