pipeline {
    agent {
        kubernetes {
            label 'jenkins-jenkins-agent-harbor'
        }
    }
    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Run Hello World Container') {
            steps {
                script {
                    docker.image('hello-world').run()
                }
            }
        }
        // stage('Checkout') {
        //     steps {
        //         cleanWs()
        //         checkout scm
        //     }
        // }

        // stage('Create or Update Jobs and Folders') {
        //     steps {
        //         script {
        //             final Map additionalParams = [
        //                         disableAllJobs: env.JOB_NAME.contains('/'),
        //                         default_ci_repo: params.default_ci_repo
        //                     ]
        //             jobDsl(additionalClasspath: 'infrastructure/dsl/pipeline_job',
        //                 lookupStrategy: 'SEED_JOB',                        
        //                 // targets: ['jenkins/dsl/jobs/**/*.groovy'].join('\n'),                
        //                 targets: ['infrastructure/dsl/pipeline_job/DSL*.groovy'].join('\n'),                
        //                 removedJobAction: 'DELETE', // Action to take on removed jobs
        //                 additionalParameters: additionalParams)
        //             println "Done processing DSL scripts"    
                                        
        //         }
        //     }
        // }
    }
}